server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${pocket.datasource.driver-class-name}
      url: jdbc:mysql://${pocket.datasource.host}:${pocket.datasource.port}/${pocket.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${pocket.datasource.username}
      password: ${pocket.datasource.password}
  redis:
    host: ${pocket.redis.host}
    port: ${pocket.redis.port}
    password: ${pocket.redis.password}
    database: ${pocket.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pocket.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      pocket:
        mapper: debug
        service: info
        controller: info

pocket:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: sqnugy_admin
    # 设置jwt过期时间
    admin-ttl: 788923800000 #25年
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: sqnugy_user
    user-ttl: 788923800000
    user-token-name: authentication
  alioss:
    endpoint: ${pocket.alioss.endpoint}
    access-key-id: ${pocket.alioss.access-key-id}
    access-key-secret: ${pocket.alioss.access-key-secret}
    bucket-name: ${pocket.alioss.bucket-name}
  wechat:
    appid: ${pocket.wechat.appid}
    secret: ${pocket.wechat.secret}